# Generated by Django 5.2.9 on 2025-12-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
